---
- hosts: 172.31.9.178
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: create myfolder
    file: 
      path: /home/ubuntu/myfolder
      state: directory
  - name: copy file from master to node side
    copy: 
       src: my2ndfile.txt
       dest: /home/ubuntu/my2ndfile
  - name: install apache2
    apt: 
      name: apache2
      state: present
  - name: copy dynamic file into node side
    template: 
         src: myindex.j2
         dest: /var/www/html/index.html 
  